import React, { useEffect, useState } from "react";
import { RefreshCw, ChevronDown } from "lucide-react";
import { api } from "../api.js";

export default function AutomationHistoryView() {
  const [automations, setAutomations] = useState([]); const [selected, setSelected] = useState(""); const [runs, setRuns] = useState([]); const [chain, setChain] = useState(null);
  const load = async () => { const xs = await api.listAutomations(); setAutomations(xs); if (xs[0]) { setSelected(xs[0].id); setRuns(await api.automationRuns(xs[0].id)); } };
  useEffect(() => { load().catch(() => {}); }, []);
  const choose = async (id) => { setSelected(id); setChain(null); setRuns(await api.automationRuns(id)); };
  const showChain = async (eventId) => setChain(await api.eventChain(eventId));
  return <div className="mx-auto max-w-[1000px] px-4 py-6"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-bold">История автоматизаций</h1><p className="text-sm text-slate-500">Событие → запуск → результат</p></div><button className="btn btn-secondary" onClick={() => load().catch(() => {})}><RefreshCw className="h-4 w-4" /> Обновить</button></div>{automations.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-400">Запусков пока нет</div> : <><select className="input mb-3 max-w-md" value={selected} onChange={(e) => choose(e.target.value)}>{automations.map((a) => <option value={a.id} key={a.id}>{a.name}</option>)}</select><div className="space-y-2">{runs.map((run) => <div key={run.id} className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-3"><span className={run.status === "SUCCESS" ? "font-semibold text-emerald-600" : "font-semibold text-red-600"}>{run.status}</span><span className="text-sm text-slate-500">{new Date(run.started_at).toLocaleString()}</span><button className="btn btn-ghost btn-sm ml-auto" onClick={() => showChain(run.event_id)}><ChevronDown className="h-3.5 w-3.5" /> Цепочка</button></div>{run.error && <div className="mt-2 text-xs text-red-600">{run.error}</div>}{run.result && <div className="mt-2 text-xs text-slate-500">Действий: {run.result.actions || 0} · задач: {run.result.tasks || 0} · уведомлений: {run.result.notifications || 0}</div>}</div>)}</div></>}{chain && <div className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4"><h2 className="mb-2 font-semibold text-indigo-800">Цепочка событий</h2><div className="space-y-1">{chain.map((event) => <div key={event.id} className="rounded bg-white px-3 py-2 text-xs"><b>{event.type}</b> · {event.entity_type} · {new Date(event.created_at).toLocaleString()}</div>)}</div></div>}</div>;
}
