import React, { useEffect, useState } from "react";
import { Plus, Trash2, Play, Power } from "lucide-react";
import { api } from "../api.js";

const EMPTY = { name: "", trigger_type: "project.deadline_approaching", conditions: { conditions: [{ field: "stage", operator: "not_equals", value: "Завершён" }] }, actions: [{ type: "notification", title: "Проект требует внимания", message: "Проверьте проект", priority: "HIGH" }] };
const TRIGGERS = [["project.created", "Проект создан"], ["project.updated", "Проект изменён"], ["project.deadline_approaching", "Дедлайн приближается"], ["project.deadline_overdue", "Дедлайн просрочен"], ["task.completed", "Задача завершена"], ["payment.updated", "Оплата изменена"]];
export default function AutomationsView() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState(null); const [busy, setBusy] = useState(false); const [test, setTest] = useState(null); const [templates, setTemplates] = useState([]);
  const load = () => Promise.all([api.listAutomations(), api.listAutomationTemplates()]).then(([a, t]) => { setRows(a); setTemplates(t); }).catch(() => {}); useEffect(load, []);
  const save = async () => { setBusy(true); try { const x = await api.createAutomation(form); setRows((r) => [x, ...r]); setForm(null); } finally { setBusy(false); } };
  const toggle = async (a) => { const x = a.enabled ? await api.disableAutomation(a.id) : await api.enableAutomation(a.id); setRows((r) => r.map((z) => z.id === x.id ? x : z)); };
  const remove = async (a) => { if (window.confirm(`Удалить «${a.name}»?`)) { await api.deleteAutomation(a.id); setRows((r) => r.filter((z) => z.id !== a.id)); } };
  return <div className="mx-auto max-w-[1000px] px-4 py-6"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-bold">Автоматизации</h1><p className="text-sm text-slate-500">WHEN → IF → THEN</p></div><button className="btn btn-primary" onClick={() => setForm({...EMPTY})}><Plus className="h-4 w-4" /> Создать</button></div>
    {form && templates.length > 0 && <div className="mb-3 flex flex-wrap gap-1.5"><span className="self-center text-xs text-slate-500">Шаблон:</span>{templates.map((t) => <button key={t.key} className="btn btn-secondary btn-sm" onClick={() => setForm({ ...t, name: t.name })}>{t.name}</button>)}</div>}
    <div className="space-y-2">{rows.map((a) => <div key={a.id} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><button onClick={() => toggle(a)} className={a.enabled ? "text-emerald-600" : "text-slate-300"} title="Включить/выключить"><Power className="h-4 w-4" /></button><div className="min-w-0 flex-1"><div className="font-semibold">{a.name}</div><div className="text-xs text-slate-500">WHEN {a.trigger_type} · {(a.actions || []).length} action(s)</div></div><button className="btn btn-secondary btn-sm" onClick={() => api.testAutomation(a.id).then(setTest)}><Play className="h-3.5 w-3.5" /> Проверить</button><button className="btn btn-ghost btn-icon-sm text-red-500" onClick={() => remove(a)}><Trash2 className="h-4 w-4" /></button></div>)}</div>
    {rows.length === 0 && <div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-400">Автоматизаций пока нет</div>}
    {form && <Builder form={form} setForm={setForm} onCancel={() => setForm(null)} onSave={save} busy={busy} />}
    {test && <div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-slate-900/40" onClick={() => setTest(null)} /><div className="relative w-[420px] rounded-xl bg-white p-5"><h3 className="font-semibold">Тест автоматизации</h3><p className="mt-2 text-sm">Подходящих проектов: {test.matched?.length || 0}</p><p className="text-sm">Будет создано задач: {test.would_create_tasks || 0}</p><button className="btn btn-primary mt-4" onClick={() => setTest(null)}>Закрыть</button></div></div>}
  </div>;
}
function Builder({form,setForm,onCancel,onSave,busy}) { const cond = form.conditions.conditions[0]; const patch = (p) => setForm({...form,...p}); return <div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-slate-900/40" onClick={onCancel} /><div className="relative w-[520px] max-w-[95vw] rounded-xl bg-white p-5 shadow-xl"><h2 className="mb-4 text-lg font-bold">Новая автоматизация</h2><label className="label">Название</label><input className="input" value={form.name} onChange={(e) => patch({name:e.target.value})} placeholder="Напоминание о дедлайне" /><div className="mt-4 rounded-lg bg-indigo-50 p-3"><b className="text-xs text-indigo-700">WHEN</b><select className="input mt-1" value={form.trigger_type} onChange={(e) => patch({trigger_type:e.target.value})}>{TRIGGERS.map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></div><div className="mt-3 rounded-lg bg-amber-50 p-3"><b className="text-xs text-amber-700">IF</b><div className="mt-1 flex gap-1"><select className="input" value={cond.field} onChange={(e) => patch({conditions:{conditions:[{...cond,field:e.target.value}]}})}><option value="stage">Этап</option><option value="risk_level">Риск</option><option value="payment_percent">Оплата</option></select><select className="input" value={cond.operator} onChange={(e) => patch({conditions:{conditions:[{...cond,operator:e.target.value}]}})}><option value="equals">равно</option><option value="not_equals">не равно</option><option value="lt">меньше</option></select><input className="input" value={cond.value} onChange={(e) => patch({conditions:{conditions:[{...cond,value:e.target.value}]}})} /></div></div><div className="mt-3 rounded-lg bg-emerald-50 p-3"><b className="text-xs text-emerald-700">THEN</b><select className="input mt-1" value={form.actions[0].type} onChange={(e) => patch({actions:[{...form.actions[0],type:e.target.value}]})}><option value="notification">Создать уведомление</option><option value="create_task">Создать задачу</option></select>{form.actions[0].type === "create_task" && <input className="input mt-1" placeholder="Название задачи" value={form.actions[0].title || ""} onChange={(e) => patch({actions:[{...form.actions[0],title:e.target.value}]})} />}</div><div className="mt-5 flex justify-end gap-2"><button className="btn btn-ghost" onClick={onCancel}>Отмена</button><button className="btn btn-primary" disabled={busy || !form.name.trim()} onClick={onSave}>Сохранить</button></div></div></div>; }
