import React, { useEffect, useState } from "react";
import { Bell, RefreshCw } from "lucide-react";
import { api } from "../api.js";

export default function NotificationSettingsView() {
  const [prefs, setPrefs] = useState([]); const [automations, setAutomations] = useState([]); const [runs, setRuns] = useState([]); const [busy, setBusy] = useState(false); const [selectedAutomation, setSelectedAutomation] = useState("");
  const load = async () => { const [p, a] = await Promise.all([api.getNotificationPreferences(), api.listAutomations()]); setPrefs(p); setAutomations(a); if (a[0]) setRuns(await api.automationRuns(a[0].id)); };
  useEffect(() => { load().catch(() => {}); }, []);
  useEffect(() => { if (automations[0] && !selectedAutomation) setSelectedAutomation(automations[0].id); }, [automations, selectedAutomation]);
  const save = async (value) => { setBusy(true); try { const x = await api.setNotificationPreferences(value); setPrefs((old) => [...old.filter((p) => p.category !== x.category), x]); } finally { setBusy(false); } };
  const current = (category) => prefs.find((p) => p.category === category) || { category, in_app: true, email: false, telegram: false, quiet_start: "22:00", quiet_end: "08:00" };
  return <div className="mx-auto max-w-[1000px] px-4 py-6"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-bold">Настройки уведомлений</h1><p className="text-sm text-slate-500">Каналы и история автоматизаций</p></div><button className="btn btn-secondary" onClick={() => load().catch(() => {})}><RefreshCw className="h-4 w-4" /> Обновить</button></div>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 flex items-center gap-2 font-semibold"><Bell className="h-4 w-4 text-indigo-600" /> Каналы</h2><div className="space-y-3">{["deadlines", "risks", "tasks"].map((category) => { const p = current(category); return <div key={category} className="flex flex-wrap items-center gap-3 border-b border-slate-100 pb-3 last:border-0"><span className="w-28 text-sm font-medium">{category === "deadlines" ? "Дедлайны" : category === "risks" ? "Риски" : "Задачи"}</span>{["in_app", "email", "telegram"].map((channel) => <label key={channel} className="flex items-center gap-1 text-sm text-slate-600"><input type="checkbox" checked={!!p[channel]} disabled={busy} onChange={(e) => save({...p, [channel]: e.target.checked})} /> {channel === "in_app" ? "In-app" : channel[0].toUpperCase() + channel.slice(1)}</label>)}</div>; })}</div><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><span>Тихие часы</span><input className="input w-24" value={current("deadlines").quiet_start} onChange={(e) => save({...current("deadlines"), quiet_start:e.target.value})} /><span>—</span><input className="input w-24" value={current("deadlines").quiet_end} onChange={(e) => save({...current("deadlines"), quiet_end:e.target.value})} /></div></section>
    <section className="mt-5 rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">История запусков</h2>{automations.length === 0 ? <p className="text-sm text-slate-400">Запусков пока нет.</p> : <><select className="input mb-3 max-w-md" value={selectedAutomation} onChange={(e) => { setSelectedAutomation(e.target.value); api.automationRuns(e.target.value).then(setRuns); }}>{automations.map((a) => <option value={a.id} key={a.id}>{a.name}</option>)}</select><div className="space-y-1">{runs.map((r) => <div key={r.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{new Date(r.started_at).toLocaleString()}</span><span className={r.status === "SUCCESS" ? "text-emerald-600" : "text-red-600"}>{r.status}</span><span className="text-xs text-slate-500">{r.error || `${r.result?.actions || 0} actions`}</span></div>)}</div></>}</section>
  </div>;
}