"""scripts_01/taxonomy_gap_report.py — TAXONOMY gap analysis (deterministic vs LLM).

Runs both extractors on a project task file and computes INFERRED gaps the
deterministic extractor missed (LLM-derived capabilities not in TAXONOMY rows
fired for this text). Categorizes:
  - Section A: in TAXONOMY but regex did NOT fire on this text → need better
    keyword trigger (or accept LLM as primary path).
  - Section B: NOT in TAXONOMY at all → need new row с appropriate regex.

Output: ``<project_root>/TAXONOMY_GAP_REPORT.md`` — actionable
TAXONOMY-expansion guide for systematic vocabulary growth.

NO side-effects on global state: pure read-only analysis, only writes the report
file (в project root). Reproducible via fixed curated mock when real LLM
unavailable (per designer contract).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Set

from core_02.capability_gap_auditor import (
    TAXONOMY,
    _extract_capabilities_from_text,
    _parse_llm_response,
)
from scripts_01._curated_llm_gateway import CuratedLlmGateway


DEFAULT_OUTPUT = "TAXONOMY_GAP_REPORT.md"
DEFAULT_TASK_CANDIDATES: tuple[str, ...] = (
    "задача.md", "task.md", "promt1.md", "brief.md", "README.md",
)


def _resolve_task_file(project_root: Path, task_arg: str | None) -> Path | None:
    """Find first existing + non-empty task file. ``--task-file`` overrides candidates."""
    if task_arg:
        p = project_root / task_arg
        return p if p.is_file() and p.stat().st_size > 60 else None
    for cand in DEFAULT_TASK_CANDIDATES:
        p = project_root / cand
        if p.is_file() and p.stat().st_size > 60:
            return p
    return None


def build_gap_analysis(
    text: str,
    curated_response: str,
    *,
    taxonomy: tuple = TAXONOMY,
) -> dict:
    """Pure-function analysis: deterministic ∪ LLM-vs-deterministic diff.

    Returns dict with deterministic_ids, llm_ids, inferred_gaps, sec_a, sec_b.
    """
    det_entries = _extract_capabilities_from_text(text)
    det_ids: Set[str] = {e[0] for e in det_entries}
    parsed = _parse_llm_response(curated_response)
    llm_ids: Set[str] = {e["item_id"] for e in parsed}
    inferred_llm_ids: Set[str] = {e["item_id"] for e in parsed if not e.get("explicit")}
    # INFERRED gaps: cap that LLM infers but keyword/regex doesn't fire.
    # (LLM items matching EXPLICIT override are NOT gaps — deterministic confirms them.)
    inferred_gaps: Set[str] = inferred_llm_ids - det_ids
    taxonomy_ids: Set[str] = {entry[1] for entry in taxonomy}
    sec_a: Set[str] = inferred_gaps & taxonomy_ids
    sec_b: Set[str] = inferred_gaps - taxonomy_ids
    return {
        "deterministic_ids": det_ids,
        "llm_ids": llm_ids,
        "inferred_gaps": inferred_gaps,
        "sec_a_in_taxonomy_not_matched": sec_a,
        "sec_b_not_in_taxonomy": sec_b,
        "llm_parsed": parsed,
    }


def render_report(project_name: str, task_file_rel: str, analysis: dict) -> str:
    """Render Markdown report (pure function, no IO)."""
    det_ids = analysis["deterministic_ids"]
    llm_ids = analysis["llm_ids"]
    inferred_gaps = analysis["inferred_gaps"]
    sec_a = sorted(analysis["sec_a_in_taxonomy_not_matched"])
    sec_b = sorted(analysis["sec_b_not_in_taxonomy"])

    lines: List[str] = []
    lines += [
        f"# TAXONOMY Gap Report — `{project_name}`",
        "",
        "_Generated by `scripts_01/taxonomy_gap_report.py` (curated LLM gateway — deterministic mock; not a real LLM)._",
        "",
        "## Inputs",
        "",
        f"- **Task file:** `{task_file_rel}`",
        f"- Deterministic caps (keyword/regex): {len(det_ids)}",
        f"- LLM (curated) caps: {len(llm_ids)}",
        f"- INFERRED gap (LLM \\\\ det): {len(inferred_gaps)}",
        f"- EXPLICIT overlap (LLM ∩ det): {len(llm_ids & det_ids)}",
        "",
        "## Deterministic baseline (`_extract_capabilities_from_text` direct)",
        "",
    ]
    for cap in sorted(det_ids):
        lines.append(f"- `{cap}`")
    lines.append("")

    lines += [
        "## Section A — In TAXONOMY but NOT keyword-matched on this text",
        "",
        "These capabilities exist в `TAXONOMY`, but the regex did NOT fire on this specific task text.",
        "Action: either (a) `expand TAXONOMY` — add new regex branches to existing entry,",
        "or (b) accept LLM path as primary for these capabilities.",
        "",
    ]
    if sec_a:
        for cap in sec_a:
            lines.append(f"- `{cap}`")
    else:
        lines.append("- (none — full TAXONOMY coverage)")
    lines.append("")

    lines += [
        "## Section B — NOT-IN-TAXONOMY (new entries needed)",
        "",
        "LLM-inferred capabilities that have NO existing TAXONOMY row.",
        "Action: **add new entry** with appropriate regex (rationale for each captured in `_provenance`).",
        "",
    ]
    if sec_b:
        # Annotate each Section B with its provenance from the LLM response.
        provenance_by_cap = {item["item_id"]: item.get("_provenance", "—")
                             for item in analysis["llm_parsed"]}
        for cap in sec_b:
            prov = provenance_by_cap.get(cap, "—")
            lines.append(f"- `{cap}` — {prov}")
    else:
        lines.append("- (none — TAXONOMY is complete for this task)")
    lines.append("")

    lines += [
        "## Methodology",
        "",
        "1. Read task file from `<project_root>` (default candidates: задача.md / task.md / promt1.md / brief.md / README.md).",
        "2. Deterministic extractor: `_extract_capabilities_from_text(text)` → keyword/regex match against `TAXONOMY`.",
        "3. LLM extractor: `_parse_llm_response(curated_gateway_return)` — parse curated 18-cap JSON (mock excluding реальный LLM).",
        "4. Diff: `inferred_gaps = llm_ids - deterministic_ids` (capabilities LLM finds that regex misses).",
        "5. Categorize: cross-reference with `TAXONOMY[:][1]` (item_id set)",
        "   → **Section A** (in TAXONOMY, missing keyword trigger)",
        "   → **Section B** (NOT in TAXONOMY, needs new row).",
        "",
        "## Reproducibility",
        "",
        "Re-run from repo root:",
        "",
        "```bash",
        "python -m scripts_01.taxonomy_gap_report projects_17/vocal",
        "```",
        "",
        "_No side-effects, no global mutation, ADR-016 fail-safe._",
        "",
    ]
    return "\n".join(lines)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="taxonomy_gap_report",
        description="Analyze TAXONOMY coverage gaps (deterministic vs LLM) for a project.",
    )
    parser.add_argument(
        "project_root", type=Path,
        help="Path to project root containing a task file (задача.md / task.md / etc.)",
    )
    parser.add_argument(
        "--task-file", type=str, default=None,
        help="Override task-file path (relative to project_root).",
    )
    parser.add_argument(
        "--output", type=str, default=DEFAULT_OUTPUT,
        help=f"Output filename (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--gateway-response", type=str, default=None,
        help="Override curated gateway response (JSON-string). For tests/fixtures.",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Print diff (deterministic_llm_secA_secB) as JSON to stdout instead of writing report.",
    )
    args = parser.parse_args(argv)

    project_root = args.project_root
    if not project_root.is_dir():
        sys.stderr.write(f"error: project_root {project_root} не существует или не директория\n")
        return 2

    task_path = _resolve_task_file(project_root, args.task_file)
    if task_path is None:
        sys.stderr.write(
            f"error: no task file found in {project_root} "
            f"(candidates: {', '.join(DEFAULT_TASK_CANDIDATES)})\n"
        )
        return 2

    text = task_path.read_text(encoding="utf-8")
    task_rel = task_path.relative_to(project_root).as_posix()

    gw = CuratedLlmGateway(response_content=args.gateway_response)
    curated_response = gw.generate_by_capabilities([], []).content

    analysis = build_gap_analysis(text, curated_response)

    if args.json:
        import json as _json
        sys.stdout.write(_json.dumps(
            {
                "task_file": task_rel,
                "deterministic_ids": sorted(analysis["deterministic_ids"]),
                "llm_ids": sorted(analysis["llm_ids"]),
                "inferred_gaps": sorted(analysis["inferred_gaps"]),
                "sec_a_in_taxonomy_not_matched": sorted(analysis["sec_a_in_taxonomy_not_matched"]),
                "sec_b_not_in_taxonomy": sorted(analysis["sec_b_not_in_taxonomy"]),
            }, ensure_ascii=False, indent=2,
        ) + "\n")
        return 0

    report_md = render_report(project_root.name, task_rel, analysis)
    out_path = project_root / args.output
    out_path.write_text(report_md + "\n", encoding="utf-8")
    sys.stdout.write(
        f"✅ {out_path.relative_to(project_root)} written "
        f"(A={len(analysis['sec_a_in_taxonomy_not_matched'])}, "
        f"B={len(analysis['sec_b_not_in_taxonomy'])})\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
