"""Workspace OS v17 Boundaries registry — per §37 §37.7 18-boundary compliance table.

Mirrors WORKSPACE_OS_ARCHITECTURE_RESEARCH_V1.md §37.7 (B1-B14 original + B15-Collab +
B16-Exec + B17-Gov + B-GUI). Each boundary has state, owner, scope, and rule-set.

Generated by Phase 5 Forward-action #1 (~30 LOC).
"""
from dataclasses import dataclass
from enum import Enum


class BState(Enum):
    """Boundary enforcement state per §37.7 compliance table."""
    ENFORCED = "ENFORCED"
    PARTIAL = "PARTIAL"
    DOCTRINE = "DOCTRINE"


class BOwner(Enum):
    """Boundary ownership layer per §37.7."""
    WORKSPACE = "core_02/workspace.py"
    FORGE = "core_02/forge_pipeline.py"
    REGISTRY = "core_02/forge_registry.py"
    WIZARD = "core_02/wizard_lib.py"
    SCENARIO = "core_02/scenario_registry.py"
    ROUTER = "core_02/router.py"
    MEMORY = "core_02/memory_store.py"
    EVENTBUS = "scripts_01/event_bus.py"
    ORCHESTRATOR = "scripts_01/orchestrator.py"
    EXEC = "core_02/exec_layer"  # NEW per §37.2.B
    COLLAB = "core_02/collab_layer"  # NEW per §37.2.A
    GOV = "core_02/dis_engine"  # NEW per §37.2.C
    GUI = "core_02/boundaries_v17.py"  # NEW B-GUI
    LP = "ROADMAP-FR-001"  # Long-lived project doctrine


@dataclass(frozen=True)
class Boundary:
    """Architectural boundary specification per §32 + §37.7."""
    b_id: str
    description: str
    state: BState
    owner: BOwner
    scope: str  # "global" / "workspace" / "project" / "sub-project" / "stage"
    allowed: str  # natural-language allow-rule
    disallowed: str  # natural-language deny-rule
    tolerance: str  # natural-language tolerance-allowance
    namespace: str  # qualified-ID prefix pattern

    def blurb(self) -> str:
        return (f"B{b_id.lstrip("B")) ({self.state.value}, owner={self.owner.value)): "
                f"{self.description[:60]}...")


# 18 boundaries per §37.7 compliance table
BOUNDARIES_V17 = {
    "B1": Boundary(
        b_id="B1", description="Workspace⊨Engine container isolation",
        # ENFORCED с 2026-08-10 (промт 68, R-123): forge register →
        # auto-registration в WorkspaceRegistry (workspace↔project mapping).
        state=BState.ENFORCED, owner=BOwner.WORKSPACE, scope="global",
        allowed="Workspace architectural invariants",
        disallowed="Cross-workspace state mutation",
        tolerance="eventual consistency <5s",
        namespace="ws:workspace_id"),
    "B2": Boundary(
        b_id="B2", description="Project⊨Engine container isolation",
        # ENFORCED с 2026-08-10 (промт 68, R-124): ForgePipeline
        # project_read_only — Forge не мутирует состояние Project напрямую.
        state=BState.ENFORCED, owner=BOwner.WORKSPACE, scope="project",
        allowed="Project-only Forge scope",
        disallowed="Project escape to parent workspace",
        tolerance="eventual consistency <5s",
        namespace="proj:workspace_id:project_id"),
    "B3": Boundary(
        b_id="B3", description="Forge⊨Scenario orthogonal-State",
        state=BState.ENFORCED, owner=BOwner.WIZARD, scope="project",
        allowed="Wizard evolution, Scenario registry",
        disallowed="Forge-state reads from Scenario",
        tolerance="eventual consistency <1s",
        namespace="fc:project_id:scenario_id"),
    "B4": Boundary(
        b_id="B4", description="Agent⊨Phase lifecycle",
        state=BState.ENFORCED, owner=BOwner.ROUTER, scope="global",
        allowed="Agent registration per capability",
        disallowed="Phase-without-Agent execution",
        tolerance="strict (compile-time)",
        namespace="agent:agent_type"),
    "B5": Boundary(
        b_id="B5", description="Workspace-Profile metadata",
        state=BState.ENFORCED, owner=BOwner.WORKSPACE, scope="workspace",
        allowed="Workspace registration with profile",
        disallowed="Workspace without profile",
        tolerance="eventual consistency <1h",
        namespace="wsprof:workspace_id"),
    "B6": Boundary(
        b_id="B6", description="Mode⊨Scope person/agent-mix",
        state=BState.ENFORCED, owner=BOwner.ROUTER, scope="global",
        allowed="Mode per §10 A-G",
        disallowed="Cross-mode state mutation",
        tolerance="eventual consistency <1s",
        namespace="mode:mode_id"),
    "B7": Boundary(
        b_id="B7", description="Forge scoped to Project (sub-Project for cross-Project)",
        state=BState.PARTIAL, owner=BOwner.FORGE, scope="project",
        allowed="Forge per Project / sub-Project",
        disallowed="Forge unbounded to Project",
        tolerance="eventual consistency <1s",
        namespace="forge:project_id:sub_project_id"),
    "B8": Boundary(
        b_id="B8", description="Capability⊨State",
        state=BState.ENFORCED, owner=BOwner.ROUTER, scope="global",
        allowed="Capability-check at SmartRouter",
        disallowed="State without capability",
        tolerance="strict (compile-time)",
        namespace="cap:capability_id"),
    "B9": Boundary(
        b_id="B9", description="L4 Registry = single-writer",
        state=BState.PARTIAL, owner=BOwner.REGISTRY, scope="global",
        allowed="Single-writer pattern (forge_pipeline atomic_write)",
        disallowed="Multi-writer concurrent write",
        tolerance="single-writer strict",
        namespace="reg:project_id"),
    "B10": Boundary(
        b_id="B10", description="L5 Memory = transactional",
        # ENFORCED с 2026-08-10 (промт 68, R-127): ForgeRegistry.validate_schema
        # — машинно-проверяемая семантика UNFORGED vs UNTESTED (schema-violations).
        state=BState.ENFORCED, owner=BOwner.MEMORY, scope="global",
        allowed="Transactional writes (begin/commit)",
        disallowed="Bare write without transaction",
        tolerance="transactional",
        namespace="mem:project_id:kind"),
    "B11": Boundary(
        b_id="B11", description="Mode⊨Scenario composition",
        state=BState.ENFORCED, owner=BOwner.WIZARD, scope="project",
        allowed="Scenario orchestrates Mode",
        disallowed="Scenario collapses Mode",
        tolerance="eventual consistency <1s",
        namespace="mode:scenario_id"),
    "B12": Boundary(
        b_id="B12", description="Workspace OS operating environment",
        state=BState.PARTIAL, owner=BOwner.LP, scope="global",
        allowed="Operating environment doctrine",
        disallowed="Workspace OS collides with adjacent doctrine",
        tolerance="doctrinal",
        namespace="wos:concept_id"),
    "B13": Boundary(
        b_id="B13", description="Phase⊨Report each stage",
        state=BState.ENFORCED, owner=BOwner.FORGE, scope="stage",
        allowed="Report per phase",
        disallowed="Phase without Report",
        tolerance="strict (compile-time)",
        namespace="phase:stage_id"),
    "B14": Boundary(
        b_id="B14", description="Edge⊨Capability",
        state=BState.ENFORCED, owner=BOwner.ROUTER, scope="global",
        allowed="Edge-capability match",
        disallowed="Edge-and-capability divergence",
        tolerance="strict (compile-time)",
        namespace="edge:cap_match"),
    "B15": Boundary(
        b_id="B15", description="Collaboration Layer (cross-cutting) — EventBus-mediated",
        state=BState.DOCTRINE, owner=BOwner.COLLAB, scope="global",
        allowed="All entities publish via EventBus",
        disallowed="Direct cross-entity state mutation",
        tolerance="eventual consistency <5s",
        namespace="collab:agent_id:role_id"),
    "B16": Boundary(
        b_id="B16", description="Execution Layer (cross-cutting) — atomic 3-phase commit",
        state=BState.PARTIAL, owner=BOwner.EXEC, scope="stage",
        allowed="status-flag → atomic-write → EventBus-publish 3-phase",
        disallowed="Mixed reads-then-writes without transaction wrapper",
        tolerance="transactional per stage",
        namespace="exec:project_id:stage_id"),
    "B17": Boundary(
        b_id="B17", description="Governance Layer (cross-cutting) — ADR/CON/PB registry",
        state=BState.ENFORCED, owner=BOwner.GOV, scope="global",
        allowed="All decisions log in DECISIONS/LESSONS registries",
        disallowed="Bypass-architecture decisions",
        tolerance="registry eventually consistent <1h",
        namespace="gov:r-id"),
    "B-GUI": Boundary(
        b_id="B-GUI", description="UI/headless separation (B-Sec1 derivative)",
        state=BState.ENFORCED, owner=BOwner.GUI, scope="global",
        allowed="Read-state + write-via-API",
        disallowed="Direct shell-exec from UI",
        tolerance="strict (compile-time)",
        namespace="gui:ui_id"),
}


def compliance_summary():
    """Compute §37.7 compliance breakdown."""
    from collections import Counter
    states = Counter(b.state.value for b in BOUNDARIES_V17.values())
    return states


if __name__ == "__main__":
    sum_ = compliance_summary()
    print(f"v17 boundaries: {len(BOUNDARIES_V17)}")
    for state, n in sum_.items():
        print(f"  {state}: {n}")
    for key, b in BOUNDARIES_V17.items():
        print(f"  {b.blurb()}")
