"""add avatar_url to user

Revision ID: 8c460438fa4b
Revises: 82a7cc8a277c
Create Date: 2026-03-22 18:46:24.411667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c460438fa4b'
down_revision = '82a7cc8a277c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('OFFER_CREATED', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_WITHDRAWN', 'text', name='messagetype'),
               type_=sa.Enum('OFFER_CREATED', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_WITHDRAWN', 'TEXT', name='messagetype', native_enum=False, length=50),
               existing_nullable=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('OFFER_CREATED', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_WITHDRAWN', 'TEXT', name='messagetype', native_enum=False, length=50),
               type_=postgresql.ENUM('OFFER_CREATED', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_WITHDRAWN', 'text', name='messagetype'),
               existing_nullable=False)
    # ### end Alembic commands ###

